'use strict';
(()=>{
 const video=document.querySelector('#video'),canvas=document.querySelector('#handLandmarks'),context=canvas.getContext('2d'),toggle=document.querySelector('#showLandmarks'),numbers=document.querySelector('#landmarkNumbers'),status=document.querySelector('#landmarkStatus'),retry=document.querySelector('#retryLandmarks');
 const connections=[[0,1],[1,2],[2,3],[3,4],[0,5],[5,6],[6,7],[7,8],[5,9],[9,10],[10,11],[11,12],[9,13],[13,14],[14,15],[15,16],[13,17],[0,17],[17,18],[18,19],[19,20]];
 const tips={4:'拇指',8:'食指',12:'中指',16:'无名指',20:'小指'},colors=['#ffe066','#ffb36b','#71f0c3','#79b7ff','#e6a4ff'];
 let worker=null,ready=false,inFlight=false,session=0,lastFrame=-1,latest=null,loadingTimer=null,wasActive=false,failed=false;
 const active=()=>toggle.checked&&video.srcObject&&video.readyState>=2&&!document.hidden;
 function clear(){context.clearRect(0,0,canvas.width,canvas.height);latest=null}
 function fail(message){failed=true;clearTimeout(loadingTimer);worker?.terminate();worker=null;ready=inFlight=false;session++;clear();status.textContent='关键点暂不可用：'+message+'。手势训练和比赛仍可使用。';retry.hidden=false}
 function init(){if(worker)return;status.textContent='正在加载手部关键点模型，首次可能稍慢…';retry.hidden=true;try{worker=new Worker('landmarks-worker.js?v=20261008-1');loadingTimer=setTimeout(()=>fail('加载超时，请重试'),60000);worker.onerror=()=>fail('组件加载失败');worker.onmessage=({data})=>{if(data.type==='ready'){clearTimeout(loadingTimer);ready=true;status.textContent='关键点已就绪，请把手放进画面。'}else if(data.type==='error')fail(data.message);else if(data.type==='result'){inFlight=false;if(data.session!==session||!active())return;latest=data;draw();status.textContent=data.landmarks.length?`检测到 ${data.landmarks.length} 只手 · 每只手 21 个关键点`:'没有检测到手，请让整只手清晰地进入画面。'}};worker.postMessage({type:'init'})}catch(e){fail(e.message)}}
 function draw(){clearCanvas();if(!latest||!active())return;const rect=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(rect.width*dpr);canvas.height=Math.round(rect.height*dpr);context.setTransform(dpr,0,0,dpr,0,0);const scale=Math.max(rect.width/latest.width,rect.height/latest.height),ox=(latest.width*scale-rect.width)/2,oy=(latest.height*scale-rect.height)/2;
  const xy=p=>({x:rect.width-(p.x*latest.width*scale-ox),y:p.y*latest.height*scale-oy});
  for(const hand of latest.landmarks){const points=hand.map(xy);context.lineWidth=2.5;context.strokeStyle='#76ffdc';context.shadowColor='#102040';context.shadowBlur=3;for(const[a,b]of connections){context.beginPath();context.moveTo(points[a].x,points[a].y);context.lineTo(points[b].x,points[b].y);context.stroke()}
   points.forEach((p,i)=>{if(!Number.isFinite(p.x)||!Number.isFinite(p.y))return;const color=i===0?'#ffffff':colors[Math.min(4,Math.floor((i-1)/4))];context.fillStyle=color;context.beginPath();context.arc(p.x,p.y,tips[i]?5:3.5,0,Math.PI*2);context.fill();context.lineWidth=1;context.strokeStyle='#12213c';context.stroke();if(numbers.checked||tips[i]){const text=numbers.checked?String(i):tips[i];context.font='bold 11px sans-serif';context.lineWidth=3;context.strokeStyle='#102040';context.strokeText(text,p.x+7,p.y-7);context.fillStyle=color;context.fillText(text,p.x+7,p.y-7)}})
  }
 }
 function clearCanvas(){context.setTransform(1,0,0,1,0,0);context.clearRect(0,0,canvas.width,canvas.height)}
 async function loop(){try{const on=active();if(!on){if(wasActive){session++;clear()}wasActive=false;if(!video.srcObject)status.textContent='开启摄像头后，可以查看指尖和关节关键点。'}else{wasActive=true;if(!worker&&!failed)init();if(ready&&!inFlight&&video.currentTime!==lastFrame&&!busy&&!predicting){inFlight=true;lastFrame=video.currentTime;const current=session,bitmap=await createImageBitmap(video);if(current!==session||!active()||!worker){bitmap.close();inFlight=false}else worker.postMessage({type:'frame',bitmap,session:current,time:performance.now()},[bitmap])}}}catch(e){fail(e.message)}finally{setTimeout(loop,180)}}
 toggle.onchange=()=>{session++;clear();status.textContent=toggle.checked?'等待摄像头画面…':'关键点显示已关闭。'};numbers.onchange=draw;retry.onclick=()=>{failed=false;worker?.terminate();worker=null;ready=inFlight=false;session++;init()};new ResizeObserver(draw).observe(canvas);window.addEventListener('pagehide',()=>{worker?.terminate();clearTimeout(loadingTimer)});loop();
})();
