'use strict';
const $=s=>document.querySelector(s), names=['石头','剪刀','布'],icons=['✊','✌️','🖐️'], stepNames=['采集照片','训练模型','实时检验','两轮对比','教比赛规则','猜拳擂台'];
const sets={A:[[],[],[]],B:[[],[],[]],T:[[],[],[]]}, revisions={A:0,B:0,T:0},models={A:null,B:null};
const MIN_SAMPLES=5, TRAIN_EPOCHS=60;
let rules=null,ruleDraft=['','',''],tieDraft='',ruleMessage='';
let cameraAttempt=0;
let step=0,pool='A',label=0,stream=null,base=null,basePromise=null,busy=false,trainBusy=false,taskToken=0,nextId=1,lastPred=null,predicting=false,liveKey='A',compareResult=null,game={phase:'idle',computer:null,player:null,score:[0,0,0],message:'训练你的模型，来一场公平的对决。'},sequence=[];
const video=$('#video'),sampleCanvas=document.createElement('canvas');sampleCanvas.width=sampleCanvas.height=224;const ctx=sampleCanvas.getContext('2d',{willReadFrequently:true});
function counts(k){return sets[k].map(a=>a.length)}
function countHTML(k){return `<div class="counts">${names.map((n,i)=>`<span>${icons[i]} ${n} ${sets[k][i].length} 张</span>`).join('')}</div>`}
function status(t){const el=$('#actionStatus');if(el)el.textContent=t}
function engine(t){$('#engineStatus').textContent=t}
function isGameBusy(){return ['countdown','reading'].includes(game.phase)}
function render(){
 $('#steps').innerHTML=stepNames.map((n,i)=>`<button data-step="${i}" class="${step===i?'active':''}" ${busy||isGameBusy()?'disabled':''}><span>0${i+1}</span>${n}</button>`).join('');
 $('#modelSelect').disabled=busy||isGameBusy();$('#reset').disabled=busy||isGameBusy();
 const html=[collection,training,testing,comparison,ruleLesson,arena][step]();$('#lesson').innerHTML=html;bind();paintLive();
}
function collection(){return `<span class="tag">01 / 给模型一些例子</span><h2>你的照片，就是它的练习题。</h2><p>先选手势，再把手完整地放进中央方框拍照。</p><div class="tabs"><button data-pool="A" ${busy?'disabled':''} aria-pressed="${pool==='A'}">第一轮 A · 固定角度</button><button data-pool="B" ${busy?'disabled':''} aria-pressed="${pool==='B'}">第二轮 B · 多种角度</button></div><div class="notice ${pool==='B'?'warm':''}">${pool==='A'?'先保持正面、相近距离，收集一组例子。每类建议 20—30 张，至少 5 张可试训（照片少，容易认错）。':'试试略向左、略向右、远一点和近一点。每种手势都要拍多种角度，不要让某个角度只属于一种手势。'}</div>${classButtons(pool)}<div class="tools"><button class="primary" id="snap" ${!stream||busy?'disabled':''}>拍一张 ${names[label]}</button><button id="burst" ${!stream||busy?'disabled':''}>间隔拍 5 张</button>${pool==='B'?`<button id="copyA" ${busy?'disabled':''}>将 A 的照片补充到 B</button>`:''}</div><label class="file-label">也可以导入自己拍好的手部照片（单张不超过 10 MB）<input id="photoInput" aria-label="导入当前手势照片" type="file" accept="image/*" multiple ${busy?'disabled':''}></label><div id="actionStatus" class="status" role="status"></div>${gallery(pool)}<p class="small">每类最多 120 张。转动手腕或改变距离后再拍，连续重复同一张画面不能代替多样的例子。</p><button data-go="1" ${busy?'disabled':''}>照片准备好了，去训练</button>`}
function classButtons(k){return `<div class="classes">${names.map((n,i)=>`<button data-label="${i}" aria-pressed="${i===label}" ${busy?'disabled':''}><span class="hand">${icons[i]}</span>${n}<small>${sets[k][i].length} 张照片</small></button>`).join('')}</div>`}
function gallery(k){const arr=sets[k][label];return arr.length?`<div class="gallery">${arr.map(s=>`<div class="photo"><img src="${s.url}" alt="${names[label]}样本 ${s.id}"><button data-delete="${s.id}" aria-label="删除样本 ${s.id}" ${busy?'disabled':''}>×</button></div>`).join('')}</div>`:'<div class="empty">这个类别还没有照片。请先拍摄或导入。</div>'}
function trainingHint(k){const missing=counts(k).map((n,i)=>n<MIN_SAMPLES?`${names[i]}还差 ${MIN_SAMPLES-n} 张`:null).filter(Boolean);return `<p class="small">${missing.length?`暂时不能训练：${missing.join('；')}。`:counts(k).some(n=>n<20)?'可以开始试训了！目前例子较少，识别不稳时，每类补到 20—30 张再比较。':'照片数量已满足训练要求。请检查每张照片的手势标签是否正确。'}</p>`}
function training(){return `<span class="tag">02 / 学习照片里的规律</span><h2>把练习题交给模型。</h2><p>基础视觉模型负责提取特征，你的照片用来训练新的三类识别器。</p>${['A','B'].map(k=>`<div class="model-card"><h3>模型 ${k} · ${k==='A'?'第一轮':'第二轮'}</h3>${countHTML(k)}<p>${models[k]?`已训练 · 当时共 ${models[k].n} 张${models[k].rev!==revisions[k]?' · 照片已变化，需重新训练以应用修改':''}`:'还没有训练'}</p>${trainingHint(k)}<button class="primary" data-train="${k}" ${busy||!counts(k).every(n=>n>=MIN_SAMPLES)?'disabled':''}>${models[k]?'重新训练':'开始训练'}模型 ${k}</button></div>`).join('')}<progress id="trainProgress" value="0" max="${TRAIN_EPOCHS}"></progress><div id="actionStatus" class="status" role="status">每类至少 ${MIN_SAMPLES} 张，学习 ${TRAIN_EPOCHS} 轮。建议每类 20—30 张。训练快慢取决于设备。</div><div class="notice">训练时的表现不是考试成绩。下一步请用新的手势画面检验，识别不理想也是真实的实验发现。</div><button data-go="2" ${busy?'disabled':''}>去实时检验</button>`}
function testing(){return `<span class="tag">03 / 用新的手势挑战它</span><h2>正面会了，侧面也会吗？</h2><p>打开摄像头，在左侧选择模型 A 或 B。实时结果来自你训练的识别器。</p><div class="model-card"><h3>试一试这些变化</h3><p>① 手腕稍向左或右转。</p><p>② 手离摄像头远一点、近一点。</p><p>③ 换另一只手，或请同学来试。</p><p>④ 把手拿开，观察它是否仍会猜一个答案。</p></div><div class="notice warm">先一次改变一个条件，才能更清楚地找到原因。空画面可能被误认：三类分类器并不自动认识所有“其他东西”。</div><div class="notice"><b>剪刀总是认不准？</b>先让两根手指自然分开、完整留在方框里。给石头、剪刀、布使用相同的背景和光线；每类都拍正面、略侧面和不同距离，避免模型只记住背景。低分表示拿不准，不是你做错了。</div><p>哪种情况容易认错？回到采集区，为 B 补充有代表性的例子。不要只反复拍它已经很熟悉的姿势。</p><div class="tools"><button id="improve" class="primary">给 B 补充多角度照片</button><button data-go="3">用同一份试卷比较</button></div>`}
function classReport(res){return `<div class="model-card"><h3>每一种手势，分别认对多少？</h3>${names.map((name,y)=>{const rows=res.rows.filter(r=>r.y===y);const score=k=>rows.filter(r=>r[k]===y).length;return `<p>${icons[y]} ${name}：A ${score('a')}/${rows.length}　·　B ${score('b')}/${rows.length}</p>`}).join('')}<p class="small">这是独立测试照片的结果，不是预测分数。检查下面的错例，看看剪刀容易被认成什么。</p></div>`}
function comparison(){const res=compareResult;return `<span class="tag">04 / 同一份试卷，公平比较</span><h2>第二次训练，有进步吗？</h2><p>另拍一批测试照片，每类至少 3 张；它们不会用于训练。把训练过的照片导入这里会使成绩失真。</p>${classButtons('T')}<div class="tools"><button id="snap" class="primary" ${!stream||busy||!!res?'disabled':''}>拍一张测试照片</button><button id="clearTest" ${busy?'disabled':''}>清空试卷，重新采集</button></div><label class="file-label">导入另行拍摄的测试照片<input id="photoInput" aria-label="导入测试照片" type="file" accept="image/*" multiple ${busy||!!res?'disabled':''}></label>${!res?gallery('T'):''}<div class="tools"><button id="compare" class="primary" ${busy||!models.A||!models.B||!counts('T').every(n=>n>=3)?'disabled':''}>比较两个模型</button></div><div id="actionStatus" class="status" role="status"></div>${res?`<div class="accuracy"><div>模型 A<strong>${res.a} / ${res.n}</strong>认对 ${Math.round(res.a/res.n*100)}%</div><div>模型 B<strong>${res.b} / ${res.n}</strong>认对 ${Math.round(res.b/res.n*100)}%</div></div><p>${res.b>res.a?'这组测试中，B 认对得更多。看看哪些错例被修好了。':res.b===res.a?'这组测试中，两轮认对数量相同。看看它们是否错在同样的照片上。':'这组测试中，B 认对得更少。检查标签、照片清晰度和每类样本分布，再设计新实验。'}</p>${classReport(res)}<div class="result-list">${res.rows.map(r=>`<div class="test-result"><img src="${r.s.url}" alt="测试照片"><div>正确：${names[r.y]}<br><span class="${r.a===r.y?'pass':'fail'}">A：${names[r.a]}</span>　<span class="${r.b===r.y?'pass':'fail'}">B：${names[r.b]}</span></div></div>`).join('')}</div>`:''}<p class="small">A 训练照片 ${models.A?.n??0} 张，B 训练照片 ${models.B?.n??0} 张。${models.A&&models.B&&JSON.stringify(models.A.counts)!==JSON.stringify(models.B.counts)?'两组数量不同，结果同时受到数量和样本内容的影响。':'若每类数量相同、其他条件相近，能更好地观察角度差异的影响。'}改进模型后，请另拍新试卷做最终检验。</p><button data-go="4" ${busy?'disabled':''}>下一步：教机器比赛规则</button>`}
function ruleError(beats,tie){if(beats.some(v=>v==='')||tie==='')return '还有没说完的规则：请填满三个空，也告诉我相同手势怎么办。';const b=beats.map(Number);if(b.some((v,i)=>![0,1,2].includes(v)||v===i))return '一种手势不能打败自己，请再检查。';if(new Set(b).size!==3)return '规则打架了！请让每种手势各赢一种、各输一种，组成一个圈。';if(tie!=='draw')return '相同手势不能分出谁赢，请选择平局。';return ''}
function ruleLesson(){return `<span class="tag">05 / 你来教，机器来执行</span><h2>认得手势，还要懂规则。</h2><p>把比赛规则补充完整。你写下的规则会真的用于下一步的比赛。</p><div class="model-card"><h3>我的比赛规则</h3>${names.map((n,i)=>`<label class="rule-row">${icons[i]} ${n} 能赢 <select data-rule="${i}" aria-label="${n}能赢谁"><option value="">请选择手势</option>${names.map((v,j)=>j===i?'':`<option value="${j}" ${ruleDraft[i]===String(j)?'selected':''}>${icons[j]} ${v}</option>`).join('')}</select></label>`).join('')}<label class="rule-row">双方出一样的手势 <select id="tieRule" aria-label="相同手势的结果"><option value="">请选择结果</option><option value="draw" ${tieDraft==='draw'?'selected':''}>平局</option><option value="player" ${tieDraft==='player'?'selected':''}>我赢</option><option value="computer" ${tieDraft==='computer'?'selected':''}>电脑赢</option></select></label></div><button class="primary" id="saveRules">把规则教给机器</button><p id="ruleFeedback" role="status">${ruleMessage}</p>${rules?`<div class="notice"><b>机器复述已保存的规则：</b><br>${rules.map((v,i)=>`${icons[i]} ${names[i]} 赢 ${icons[v]} ${names[v]}`).join('；')}；相同手势算平局。<p>${rules.join(',')==='1,2,0'?'这就是常见的石头剪刀布规则！':'你设计了反向规则！比赛会按你的规则判胜负。'}</p></div>`:''}<div class="notice warm">照片教它“这是什么手势”；规则告诉它“谁赢谁”。识别和判胜负，是两件不同的事。</div><p class="small">改好后记得重新提交。提交新规则会清空比分，照片和模型保留。</p><button data-go="5" ${!rules?'disabled':''}>规则准备好了，去比赛</button>`}
function saveRules(){const error=ruleError(ruleDraft,tieDraft);if(error){ruleMessage=error;render();return}rules=ruleDraft.map(Number);game.score=[0,0,0];game.phase='idle';game.computer=game.player=null;game.revealed=false;game.frame=null;game.awarded=null;game.message='规则学会了，准备出拳！';ruleMessage='收到！我会按你提交的规则来判断胜负。';render()}
function arena(){return `<span class="tag">06 / AI 猜拳擂台</span><h2>石头、剪刀、布！</h2><p>电脑提前随机选好手势。倒计时结束，双方同时亮拳，再按你教的规则自动判胜负。</p>${!rules?'<div class="notice warm">先教会机器比赛规则，才能开赛。<button data-go="4">去教规则</button></div>':`<p class="small">本场规则：${rules.map((v,i)=>`${names[i]}赢${names[v]}`).join(' · ')} · 相同为平局</p>`}<div class="score"><span>你赢 ${game.score[0]}</span><span>电脑赢 ${game.score[1]}</span><span>平局 ${game.score[2]}</span></div><div class="arena"><div class="versus"><div class="fighter">${game.player===null?'？':icons[game.player]}<small>你 · ${game.player===null?(game.phase==='reading'?'正在识别定格画面':'准备出拳'):names[game.player]}</small></div><b>VS</b><div class="fighter">${game.revealed?icons[game.computer]:'？'}<small>电脑 · ${game.revealed?names[game.computer]:game.phase==='countdown'?'已锁定':'等待开局'}</small></div></div><h3 id="gameMessage">${game.message}</h3>${game.frame?`<img class="round-frame" src="${game.frame}" alt="倒计时结束时锁定的手势照片"><p class="small">你的出拳定格 · 本轮只判断这张画面</p>`:''}</div><div class="game-buttons"><button id="startRound" class="primary" ${busy||!rules||!stream||!models[liveKey]||isGameBusy()?'disabled':''}>${game.revealed?'再来一局':'开始 3 秒倒计时'}</button>${game.phase==='result'?'<button id="voidRound">识别错了，本轮不计分</button>':''}</div><div class="notice">看到倒计时就出拳。结束瞬间锁定你的画面，并立即亮出电脑手势；识别完成后自动计分，无需再点确认。没认清就不计分；认错可撤销本轮得分。</div><div id="actionStatus" class="status" role="status"></div><p class="small">${!stream?'请先开启摄像头。':''}${!models[liveKey]?'请先训练并选择一个模型。':''}亮拳后改变手势，不会改变本轮锁定的照片。</p>`}
function bind(){document.querySelectorAll('[data-step],[data-go]').forEach(b=>b.onclick=()=>{if(busy||isGameBusy())return;step=Number(b.dataset.step??b.dataset.go);render()});document.querySelectorAll('[data-pool]').forEach(b=>b.onclick=()=>{pool=b.dataset.pool;render()});document.querySelectorAll('[data-label]').forEach(b=>b.onclick=()=>{label=Number(b.dataset.label);render()});document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{const k=step===3?'T':pool;sets[k][label]=sets[k][label].filter(s=>s.id!==Number(b.dataset.delete));revisions[k]++;render()});if($('#snap'))$('#snap').onclick=()=>captureMany(1);if($('#burst'))$('#burst').onclick=()=>captureMany(5);if($('#photoInput'))$('#photoInput').onchange=importFiles;if($('#copyA'))$('#copyA').onclick=()=>{let n=0;sets.A.forEach((arr,i)=>arr.forEach(s=>{if(sets.B[i].length<120&&!sets.B[i].some(x=>x.sourceId===(s.sourceId||s.id))){sets.B[i].push({...s,id:nextId++,sourceId:s.sourceId||s.id});n++}}));revisions.B++;render();status(`已补充 ${n} 张 A 照片。再拍不同角度，或删除部分照片以保持数量一致。`)};document.querySelectorAll('[data-train]').forEach(b=>b.onclick=()=>train(b.dataset.train));if($('#improve'))$('#improve').onclick=()=>{pool='B';step=0;render()};if($('#clearTest'))$('#clearTest').onclick=()=>{if(!confirm('清空本轮测试照片和比较结果？训练照片与模型会保留。'))return;sets.T=[[],[],[]];revisions.T++;compareResult=null;render()};if($('#compare'))$('#compare').onclick=compare;if($('#startRound'))$('#startRound').onclick=startRound;document.querySelectorAll('[data-rule]').forEach(el=>el.onchange=()=>{ruleDraft[Number(el.dataset.rule)]=el.value;ruleMessage='规则已编辑，请提交后再比赛。';$('#ruleFeedback').textContent=ruleMessage});if($('#tieRule'))$('#tieRule').onchange=e=>{tieDraft=e.target.value;ruleMessage='规则已编辑，请提交后再比赛。';$('#ruleFeedback').textContent=ruleMessage};if($('#saveRules'))$('#saveRules').onclick=saveRules;if($('#voidRound'))$('#voidRound').onclick=voidRound;}
async function ensureBase(){if(base)return base;if(basePromise)return basePromise;basePromise=(async()=>{engine('正在加载基础视觉能力…');if(!window.tf)throw Error('学习组件没有加载，请刷新页面重试。');await tf.ready();let full=await tf.loadLayersModel('model/model.json');const layer=full.getLayer('conv_pw_13_relu');base=tf.model({inputs:full.inputs,outputs:layer.output});base.trainable=false;tf.tidy(()=>base.predict(tf.zeros([1,224,224,3])).mean([1,2]));engine('基础视觉能力已就绪 · 本机运行');return base})().catch(e=>{basePromise=null;engine('加载失败：'+e.message);throw e});return basePromise}
// Retain coarse location information alongside global appearance; identical for A and B.
function spatialFeatures(map){return tf.tidy(()=>{const global=map.mean([1,2]);const grid=tf.avgPool(map,[4,4],[3,3],'valid').reshape([map.shape[0],-1]);const unit=t=>t.div(t.norm('euclidean',1,true).add(1e-7));return tf.concat([unit(global),unit(grid)],1).div(Math.sqrt(2))})}
// Each class contributes equally even when the child collected different photo counts.
function balancedIndices(labels){const groups=[0,1,2].map(c=>labels.flatMap((v,i)=>v===c?[i]:[]));if(groups.some(g=>!g.length))throw Error('三种手势都需要照片');const n=Math.max(...groups.map(g=>g.length));return Array.from({length:n},(_,i)=>groups.map(g=>g[i%g.length])).flat()}
function embedding(canvas){return tf.tidy(()=>{const pixels=tf.browser.fromPixels(canvas).toFloat().div(127.5).sub(1).expandDims();return spatialFeatures(base.predict(pixels))})}
function crop(source){const w=source.videoWidth||source.naturalWidth||source.width,h=source.videoHeight||source.naturalHeight||source.height;if(!w||!h)throw Error('摄像头画面还没准备好');const size=Math.min(w,h);ctx.drawImage(source,(w-size)/2,(h-size)/2,size,size,0,0,224,224);return sampleCanvas}
async function storeCanvas(canvas,k,y){if(sets[k][y].length>=120)throw Error('这一类已达到 120 张，请先删除不需要的照片。');const url=canvas.toDataURL('image/jpeg',.8);if(k==='T'&&['A','B'].some(g=>sets[g].flat().some(s=>s.url===url)))throw Error('这张照片已经用于训练，请换一张新测试照片。');sets[k][y].push({id:nextId++,url,feat:null});revisions[k]++}
const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function captureMany(n){if(busy||!stream)return;busy=true;const k=step===3?'T':pool,y=label;render();try{for(let i=0;i<n;i++){if(!stream)throw Error('摄像头已关闭');await storeCanvas(crop(video),k,y);status(`已拍 ${i+1} / ${n} 张，轻轻变换手势位置。`);if(i<n-1)await delay(800)}render();status(`已为“${names[y]}”添加 ${n} 张照片。`)}catch(e){status(e.message)}finally{busy=false;const message=$('#actionStatus')?.textContent;render();status(message||'拍摄完成。')}}
async function importFiles(e){if(busy)return;const files=Array.from(e.target.files),k=step===3?'T':pool,y=label;busy=true;render();let n=0,errors=0;try{for(const file of files){try{if(file.size>10*1024*1024)throw Error();const u=URL.createObjectURL(file);try{const img=new Image();img.src=u;await img.decode();await storeCanvas(crop(img),k,y);n++}finally{URL.revokeObjectURL(u)}}catch{errors++}}}finally{busy=false;render();status(`已导入 ${n} 张${errors?`，${errors} 张未导入（超限、重复训练图或格式不支持）`:''}。`)}}
async function feature(s){if(s.feat)return s.feat;const img=new Image();img.src=s.url;await img.decode();const t=embedding(img);try{s.feat=Array.from(await t.data());return s.feat}finally{t.dispose()}}
async function train(k){if(busy||!counts(k).every(n=>n>=MIN_SAMPLES))return;busy=trainBusy=true;lastPred=null;sequence=[];render();let model=null,x=null,y=null;try{while(predicting)await delay(20);await ensureBase();const items=sets[k].flatMap((a,c)=>a.map(s=>({s,c})));const feats=[];for(let i=0;i<items.length;i++){feats.push(await feature(items[i].s));status(`正在整理照片 ${i+1} / ${items.length}`);await tf.nextFrame()}const indices=balancedIndices(items.map(v=>v.c));x=tf.tensor2d(indices.map(i=>feats[i]));y=tf.tidy(()=>tf.oneHot(tf.tensor1d(indices.map(i=>items[i].c),'int32'),3));model=tf.sequential();model.add(tf.layers.dense({inputShape:[feats[0].length],units:32,activation:'relu',kernelInitializer:tf.initializers.glorotUniform({seed:42})}));model.add(tf.layers.dense({units:3,activation:'softmax',kernelInitializer:tf.initializers.glorotUniform({seed:73})}));model.compile({optimizer:tf.train.adam(.008),loss:'categoricalCrossentropy',metrics:['accuracy']});await model.fit(x,y,{epochs:TRAIN_EPOCHS,batchSize:Math.min(24,indices.length),shuffle:true,callbacks:{onEpochEnd:async(i,logs)=>{$('#trainProgress').value=i+1;status(`学习第 ${i+1} / ${TRAIN_EPOCHS} 轮 · 训练集认对 ${Math.round((logs.acc??logs.accuracy??0)*100)}%（这不是测试成绩）`);await tf.nextFrame()}}});if(models[k]){models[k].model.optimizer?.dispose();models[k].model.dispose()}models[k]={model,n:items.length,counts:counts(k),rev:revisions[k],stamp:Date.now()};model=null;liveKey=k;$('#modelSelect').value=k;compareResult=null;status(`模型 ${k} 已训练完成。请用新的手势测试！`)}catch(e){status('训练未完成：'+e.message)}finally{model?.optimizer?.dispose();model?.dispose();x?.dispose();y?.dispose();busy=trainBusy=false;const message=$('#actionStatus')?.textContent;render();status(message)}}
function argmax(a){return a.indexOf(Math.max(...a))}
async function probabilities(m,feat){const t=tf.tidy(()=>m.model.predict(tf.tensor2d([feat])));try{return Array.from(await t.data())}finally{t.dispose()}}
async function compare(){if(busy||!models.A||!models.B)return;busy=true;sequence=[];render();try{await ensureBase();const rows=[];let a=0,b=0;for(let y=0;y<3;y++)for(const s of sets.T[y]){const f=await feature(s),pa=argmax(await probabilities(models.A,f)),pb=argmax(await probabilities(models.B,f));if(pa===y)a++;if(pb===y)b++;rows.push({s,y,a:pa,b:pb});status(`正在批改 ${rows.length} 张照片…`);await tf.nextFrame()}compareResult={a,b,n:rows.length,rows}}catch(e){status('比较失败：'+e.message)}finally{busy=false;const message=$('#actionStatus')?.textContent;render();if(!compareResult)status(message)}}
async function openCamera(){if(stream)return;const attempt=++cameraAttempt;let cameraTimer;$('#cameraStart').disabled=true;$('#cameraMessage').textContent='正在等待摄像头权限，请查看浏览器提示。';try{if(!navigator.mediaDevices?.getUserMedia)throw Error('当前页面不能调用摄像头。请用 Chrome 或 Edge 打开 HTTPS 网址或 localhost。');const request=navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:640},height:{ideal:480}},audio:false});request.then(s=>{if(attempt!==cameraAttempt)s.getTracks().forEach(t=>t.stop())}).catch(()=>{});stream=await Promise.race([request,new Promise((_,reject)=>{cameraTimer=setTimeout(()=>{cameraAttempt++;reject(Error('尚未收到摄像头授权。请允许摄像头后重试；内嵌预览受限时，请在 Chrome 或 Edge 中打开网址。'))},15000)})]);clearTimeout(cameraTimer);video.srcObject=stream;await video.play();$('#cameraPlaceholder').hidden=true;$('#cameraPlaceholder').style.display='none';$('#cameraState').textContent='摄像头已开启';$('#cameraStop').disabled=false;$('#cameraMessage').textContent='中央方框是实际识别区域。只拍手，保持完整、清晰。';stream.getVideoTracks()[0].onended=()=>stopCamera();render()}catch(e){clearTimeout(cameraTimer);if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;$('#cameraMessage').textContent=({'NotAllowedError':'摄像头未获允许。请在浏览器地址栏允许摄像头；如果是内嵌预览，请复制网址到 Chrome 或 Edge。','NotFoundError':'没有找到摄像头，请连接摄像头或使用带摄像头的电脑。','NotReadableError':'摄像头可能被其他应用占用，请关闭占用后重试。'})[e.name]||e.message;$('#cameraStart').disabled=false}}
function stopCamera(){cameraAttempt++;if(stream){stream.getTracks().forEach(t=>{t.onended=null;t.stop()})}stream=null;video.srcObject=null;$('#cameraPlaceholder').style.display='flex';$('#cameraState').textContent='摄像头未开启';$('#cameraStart').disabled=false;$('#cameraStop').disabled=true;lastPred=null;sequence=[];taskToken++;$('#countdown').hidden=true;if(isGameBusy()){game.phase='idle';game.computer=game.player=null;game.revealed=false;game.frame=null;game.message='摄像头已关闭，本轮取消，不计分。'}render();paintLive()}
function paintLive(){if(!lastPred){$('#liveName').textContent=models[liveKey]?(stream?'等待清晰画面…':'开启摄像头开始检验'):'还没有训练好的模型';$('#predictionBars').innerHTML=names.map((n,i)=>`<div class="bar-row"><span>${icons[i]} ${n}</span><div class="bar-track"><i style="width:0%"></i></div><span>—</span></div>`).join('');return}const best=argmax(lastPred.p);$('#liveName').textContent=lastPred.p[best]>=.8?`${icons[best]} 我猜是${names[best]}`:'有点拿不准，换个角度试试';$('#predictionBars').innerHTML=names.map((n,i)=>`<div class="bar-row"><span>${icons[i]} ${n}</span><div class="bar-track"><i style="width:${lastPred.p[i]*100}%"></i></div><span>${Math.round(lastPred.p[i]*100)}%</span></div>`).join('')}
async function tick(){try{if(!predicting&&!busy&&stream&&models[liveKey]&&base&&video.readyState>=2){predicting=true;const key=liveKey,t=embedding(crop(video));let f;try{f=Array.from(await t.data())}finally{t.dispose()}if(models[key]){const p=await probabilities(models[key],f);if(!busy&&stream&&key===liveKey){lastPred={p,time:Date.now(),key};const top=argmax(p);sequence.push({top,p:p[top],time:Date.now()});sequence=sequence.filter(x=>Date.now()-x.time<1400).slice(-7);paintLive()}}}}catch(e){engine('识别暂时中断：'+e.message)}finally{predicting=false;setTimeout(tick,150)}}
function randomHand(){const arr=new Uint32Array(1);do{crypto.getRandomValues(arr)}while(arr[0]>=4294967295);return arr[0]%3}
function roundOutcome(player,computer,beats){return player===computer?2:beats[player]===computer?0:1}
function finishRound(){if(game.phase!=='reading'||game.player===null)return;const result=roundOutcome(game.player,game.computer,rules);game.score[result]++;game.awarded=result;game.phase='result';game.message=['你赢啦！这一拳很精彩。','电脑赢了，再来挑战！','平局！默契的一拳。'][result];render()}
function voidRound(){if(game.phase!=='result'||game.awarded==null)return;game.score[game.awarded]--;game.awarded=null;game.phase='void';game.message='本轮得分已撤销。调整手势，再来一局！';render()}
async function startRound(){if(busy||!rules||!stream||!models[liveKey]||isGameBusy())return;const token=++taskToken,model=models[liveKey];game.computer=randomHand();game.player=null;game.frame=null;game.revealed=false;game.awarded=null;game.phase='countdown';game.message='电脑已锁定，请在倒计时结束时出拳。';render();try{for(let n=3;n>0;n--){if(token!==taskToken)return;$('#countdown').hidden=false;$('#countdown').textContent=n;await delay(1000)}if(token!==taskToken)return;
// Freeze the input before revealing the computer; later gestures cannot change this round.
const frozen=document.createElement('canvas');frozen.width=frozen.height=224;frozen.getContext('2d').drawImage(crop(video),0,0);game.frame=frozen.toDataURL('image/jpeg',.8);game.revealed=true;game.phase='reading';game.message='亮拳！正在识别你刚才的手势…';$('#countdown').hidden=true;render();await tf.nextFrame();if(token!==taskToken)return;const tensor=embedding(frozen);let feat;try{feat=Array.from(await tensor.data())}finally{tensor.dispose()}if(token!==taskToken)return;const p=await probabilities(model,feat);if(token!==taskToken)return;const top=argmax(p);if(p[top]<.8){game.phase='uncertain';game.message='这次没认清，本轮不计分。把手放稳，再试一次！'}else{game.player=top;finishRound()}}catch(e){if(token===taskToken){game.phase='uncertain';game.message='本轮未完成，不计分。'+e.message}}finally{if(token===taskToken){$('#countdown').hidden=true;render()}}}
$('#cameraStart').onclick=openCamera;$('#cameraStop').onclick=stopCamera;$('#modelSelect').onchange=e=>{liveKey=e.target.value;lastPred=null;sequence=[];paintLive()};$('#help').onclick=()=>$('#guide').showModal();$('#closeGuide').onclick=()=>$('#guide').close();$('#reset').onclick=()=>{if(!confirm('清空所有照片、模型和比分，并关闭摄像头？此操作不能撤销。'))return;stopCamera();for(const k of ['A','B','T']){sets[k]=[[],[],[]];revisions[k]=0}for(const k of ['A','B']){models[k]?.model.optimizer?.dispose();models[k]?.model.dispose();models[k]=null}rules=null;ruleDraft=['','',''];tieDraft='';ruleMessage='';compareResult=null;lastPred=null;step=0;pool='A';label=0;game={phase:'idle',computer:null,player:null,score:[0,0,0],message:'训练你的模型，来一场公平的对决。'};render();paintLive()};window.addEventListener('beforeunload',e=>{if(sets.A.flat().length+sets.B.flat().length>0){e.preventDefault();e.returnValue=''}});window.addEventListener('pagehide',()=>{stream?.getTracks().forEach(t=>t.stop())});render();paintLive();tick();
if(navigator.modelContext?.registerTool){try{navigator.modelContext.registerTool({name:'read_rps_classroom_state',description:'读取当前课堂步骤、照片数量和训练状态，不返回照片或摄像头画面。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async()=>({step:stepNames[step],counts:{A:counts('A'),B:counts('B'),test:counts('T')},trained:{A:!!models.A,B:!!models.B},busy,cameraOn:!!stream,gamePhase:game.phase})})}catch{}}
